import DOMBuilder

// Core overloads for the unified DOMBuilder
extension DOMBuilder {
    public static func buildExpression(_ el: HTMLAnchorElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLAudioElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLBRElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLBaseElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLBodyElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLButtonElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLCanvasElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLDListElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLDataElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLDataListElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLDetailsElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLDialogElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLDivElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLEmbedElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLFieldSetElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLFormElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLHRElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLHeadElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLHeadingElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLHtmlElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLIFrameElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLImageElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLInlineElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLInputElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLLIElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLLabelElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLLegendElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLLinkElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLMetaElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLMeterElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLOListElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLObjectElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLOptGroupElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLOptionElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLOutputElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLParagraphElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLParamElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLPreElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLProgressElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLQuoteElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLScriptElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLSelectElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLSourceElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLSpanElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLStyleElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLTableCaptionElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLTableCellElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLTableColElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLTableElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLTableRowElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLTableSectionElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLTextAreaElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLTimeElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLTitleElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLTrackElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLUListElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLVideoElement) -> [DOMNode] { [el.render()] }
}

// Parallel overloads for the specialized HTMLBuilder
extension HTMLBuilder {
    public static func buildExpression(_ el: HTMLAnchorElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLAudioElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLBRElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLBaseElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLBodyElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLButtonElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLCanvasElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLDListElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLDataElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLDataListElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLDetailsElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLDialogElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLDivElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLEmbedElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLFieldSetElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLFormElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLHRElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLHeadElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLHeadingElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLHtmlElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLIFrameElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLImageElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLInlineElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLInputElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLLIElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLLabelElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLLegendElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLLinkElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLMetaElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLMeterElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLOListElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLObjectElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLOptGroupElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLOptionElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLOutputElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLParagraphElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLParamElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLPreElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLProgressElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLQuoteElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLScriptElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLSelectElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLSourceElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLSpanElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLStyleElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLTableCaptionElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLTableCellElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLTableColElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLTableElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLTableRowElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLTableSectionElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLTextAreaElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLTimeElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLTitleElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLTrackElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLUListElement) -> [DOMNode] { [el.render()] }
    public static func buildExpression(_ el: HTMLVideoElement) -> [DOMNode] { [el.render()] }
}
